/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Dashboard": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Landing": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "TypeScriptFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}